---
- name: Create Supervisor directories
  loop:
    - path: "{{ supervisor_config_dir }}"
      mode: "0755"
    - path: "{{ supervisor_config_log_dir }}"
      mode: "0755"
    - path: "{{ supervisor_config_include_dir }}"
      mode: "0755"
  loop_control:
    label: "{{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: directory
    owner: root
    group: root

- name: Include variables
  loop:
    - name: Bootstrap user
      file: "{{ role_path }}/../bootstrap/vars/main/user.yml"
  run_once: true
  loop_control:
    label: "{{ item.name }}"
  ansible.builtin.include_vars: "{{ item.file }}"

- name: Copy Supervisor configuration
  ansible.builtin.template:
    src: supervisord.conf.j2
    dest: "{{ supervisor_config_file }}"
    mode: "0644"
    owner: root
    group: root

- name: Install Supervisor service
  when: ansible_virtualization_type not in ["docker"]
  block:
    - name: Install Supervisor Systemd service
      when: ansible_service_mgr == "systemd"
      notify:
        - Reload Systemd Daemon
        - Enable Supervisor service
      ansible.builtin.template:
        src: supervisord.service.j2
        dest: /etc/systemd/system/supervisord.service
        mode: "0644"

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
