---
# The root directory where Supervisor configuration files are stored.
supervisor_config_dir: /etc/supervisor

# The path to the user-specific Supervisor configuration directory.
supervisor_config_user_dir: "{{ (bootstrap_user_home_dir, '.config', 'supervisor') | ansible.builtin.path_join  }}"

# The path to the file where Supervisor configuration stored.
supervisor_config_file: "{{ (supervisor_config_dir, 'supervisord.conf') | ansible.builtin.path_join }}"

# The directory where Supervisor stores its log files.
supervisor_config_log_dir: /var/log/supervisor

# The path to the log file used by Supervisor to store runtime logs.
supervisor_config_log_file: "{{ (supervisor_config_log_dir, 'supervisor.log') | ansible.builtin.path_join }}"

# The directory where individual program configuration files are stored.
supervisor_config_include_dir: "{{ (supervisor_config_dir, 'conf.d') | ansible.builtin.path_join }}"

# The directory containing user-specific Supervisor configuration files.
supervisor_config_user_include_dir: "{{ (supervisor_config_user_dir, 'conf.d') | ansible.builtin.path_join }}"

# The space-separated list of .conf files to be included from both system and user include directories.
supervisor_config_include_files: "{{ [supervisor_config_include_dir, supervisor_config_user_include_dir] | ansible.builtin.product(['*.conf']) | map('ansible.builtin.path_join') | join(' ') }}"

# The path to the PID file where Supervisor stores its process ID.
supervisor_config_pid_file: /var/run/supervisor.pid

# The path to the Unix socket used by Supervisor for internal communication.
supervisor_config_unix_socket: /var/run/supervisor.sock

# The path to the binary of Supervisor daemon.
supervisor_config_service_daemon_binary: "{{ (supervisor_install_dir, 'bin', 'supervisord') | ansible.builtin.path_join }}"

# The path to the binary of Supervisor control.
supervisor_config_service_control_binary: "{{ (supervisor_install_dir, 'bin', 'supervisorctl') | ansible.builtin.path_join }}"
