---
name: Build Packer Images

on:
  push:
    paths:
      - docker/*
      - packer/**
      - ansible/**
      - .github/workflows/build-packer.yml

  workflow_dispatch: {}

env:
  PYTHON_VERSION: "3.13.3"
  PACKER_VERSION: "1.13.1"
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - name: archlinux
            tag: base
          - name: debian
            tag: bookworm-slim
        variant:
          - minimal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python interpreter
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Install Python modules
        run: pip install -r requirements.txt
        working-directory: ansible/

      - name: Install Packer plugins
        run: packer init .
        working-directory: packer/${{ matrix.variant }}/

      - name: Create Packer variables file
        run: |
          printf '%s\n' '{
            "docker": {
              "source_image_build":  {
                "path": "../../docker/Dockerfile.${{ matrix.distro.name }}",
                "arguments": {
                  "DISTRO_TAG": "${{ matrix.distro.tag }}"
                }
              },
              "result_image_tags": ["${{ matrix.distro.tag }}"],
              "result_image_repository": "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/coder-workspace-${{ matrix.distro.name }}-${{ matrix.variant }}"
            },
            "docker_login": {
              "server": "${{ env.DOCKER_REGISTRY }}",
              "username": "${{ env.DOCKER_USERNAME }}",
              "password": "${{ env.DOCKER_PASSWORD }}"
            }
          }' > docker.pkrvars.json
        working-directory: packer/${{ matrix.variant }}/

      - name: Build and push Docker images
        run: packer build -only=docker.workspace -var-file=docker.pkrvars.json .
        working-directory: packer/${{ matrix.variant }}/
